name: Sum

on:
  workflow_dispatch:
    inputs:
      a:
        description: 'a'
        required: true
      b:
        description: 'b'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      - name: Run script
        run: |
          python main.py ${{ github.event.inputs.a }} "${{ github.event.inputs.b }}"
